version: "3"

services:
  backend:
    build: backend/
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always

  frontend:
    build: private/
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    links:
      - backend

volumes:
  static_value:
  media_volume: