version: "3"

services:
  backend:
    build: backend/
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always

volumes:
  static_value:
  media_volume: