version: "3"

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - nginx

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/static/
      - media_volume:/app/files/
      - web-root:/usr/src/app
    depends_on:
      - backend
      - frontend

  backend:
    build: backend/
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always
    networks:
      - app-network

  frontend:
    build: private/
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - web-root:/usr/src/app
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always
    links:
      - backend
    networks:
      - app-network

volumes:
  static_value:
  media_volume:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge