version: "3"

services:
  backend:
    build: backend/
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/static/
      - media_volume:/app/files/
    depends_on:
      - backend
      - frontend

  frontend:
    build: private/
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - static_value:/app/static/
      - media_volume:/app/files/
    restart: always
    links:
      - backend

volumes:
  static_value:
  media_volume: