# Generated by Django 4.2.4 on 2023-09-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('photo', models.FileField(upload_to='')),
                ('certificates', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'About settings',
            },
        ),
        migrations.CreateModel(
            name='PageContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Contacts settings',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Privacy policy file',
            },
        ),
        migrations.CreateModel(
            name='SendEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('email_address_from', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
                ('email_address_to', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Email settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='max title length is 300 characters', max_length=300)),
                ('small_description', models.TextField()),
                ('full_description', models.TextField()),
                ('head_photo', models.FileField(upload_to='')),
                ('additional_photos', models.FileField(upload_to='')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'verbose_name_plural': 'Projects settings',
            },
        ),
    ]
