# Generated by Django 4.2.4 on 2023-09-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageabout',
            name='certificates',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
