# Generated by Django 4.2.4 on 2023-09-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pageabout_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageabout',
            name='certificates',
            field=models.FileField(upload_to='files/documents/certificates'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.FileField(upload_to='files/documents/privacy_policy'),
        ),
    ]
