# Generated by Django 4.2.3 on 2023-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workdirection_slug_alter_skill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='workdirection',
            name='slug',
            field=models.SlugField(blank=True, default=None),
        ),
    ]
