# Generated by Django 4.2.4 on 2023-09-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pageabout_certificates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='pageabout',
            name='photo',
            field=models.FileField(upload_to='files/photos/personal'),
        ),
        migrations.AddField(
            model_name='tag',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.skills'),
        ),
    ]
