# Generated by Django 4.2.3 on 2023-10-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_skill_slug_alter_workdirection_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='small_description',
            new_name='preview_description',
        ),
    ]
