# Generated by Django 4.2.4 on 2023-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skills_alter_pageabout_photo_tag_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
