# Generated by Django 4.2.3 on 2023-10-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_small_description_projects_preview_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='title',
            new_name='project_name',
        ),
    ]
