# Generated by Django 4.2.3 on 2023-10-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='max project_name length is 300 characters', max_length=300),
        ),
    ]
