# Generated by Django 4.2.4 on 2023-09-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
