# Generated by Django 4.2.3 on 2023-10-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projects_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='workdirection',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255),
        ),
    ]
