# Generated by Django 4.2.4 on 2023-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageabout',
            name='certificates',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pageabout',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
