# Generated by Django 4.2.4 on 2023-09-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pageabout_certificates_alter_pageabout_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.FileField(upload_to='certificates/')),
                ('about', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.pageabout')),
            ],
        ),
    ]
