# Generated by Django 4.2.4 on 2023-09-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='CertificatesImage',
        ),
    ]
