# Generated by Django 4.2.4 on 2023-09-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_postimage_certificatesimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageabout',
            name='certificates',
        ),
    ]
