# Generated by Django 4.2.4 on 2023-09-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pageabout_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='additional_photos',
        ),
        migrations.CreateModel(
            name='ProjectsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_photo', models.FileField(upload_to='projects/')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.projects')),
            ],
        ),
    ]
